# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import calc_pb2 as calc__pb2


class CalculatorStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.getSum = channel.unary_unary(
                '/Calculator/getSum',
                request_serializer=calc__pb2.NumberTwo.SerializeToString,
                response_deserializer=calc__pb2.Number.FromString,
                )
        self.getProduct = channel.unary_unary(
                '/Calculator/getProduct',
                request_serializer=calc__pb2.NumberTwo.SerializeToString,
                response_deserializer=calc__pb2.Number.FromString,
                )
        self.getDiff = channel.unary_unary(
                '/Calculator/getDiff',
                request_serializer=calc__pb2.NumberTwo.SerializeToString,
                response_deserializer=calc__pb2.Number.FromString,
                )
        self.getDiv = channel.unary_unary(
                '/Calculator/getDiv',
                request_serializer=calc__pb2.NumberTwo.SerializeToString,
                response_deserializer=calc__pb2.Number.FromString,
                )
        self.getSqrt = channel.unary_unary(
                '/Calculator/getSqrt',
                request_serializer=calc__pb2.Number.SerializeToString,
                response_deserializer=calc__pb2.Number.FromString,
                )


class CalculatorServicer(object):
    """Missing associated documentation comment in .proto file."""

    def getSum(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def getProduct(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def getDiff(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def getDiv(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def getSqrt(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_CalculatorServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'getSum': grpc.unary_unary_rpc_method_handler(
                    servicer.getSum,
                    request_deserializer=calc__pb2.NumberTwo.FromString,
                    response_serializer=calc__pb2.Number.SerializeToString,
            ),
            'getProduct': grpc.unary_unary_rpc_method_handler(
                    servicer.getProduct,
                    request_deserializer=calc__pb2.NumberTwo.FromString,
                    response_serializer=calc__pb2.Number.SerializeToString,
            ),
            'getDiff': grpc.unary_unary_rpc_method_handler(
                    servicer.getDiff,
                    request_deserializer=calc__pb2.NumberTwo.FromString,
                    response_serializer=calc__pb2.Number.SerializeToString,
            ),
            'getDiv': grpc.unary_unary_rpc_method_handler(
                    servicer.getDiv,
                    request_deserializer=calc__pb2.NumberTwo.FromString,
                    response_serializer=calc__pb2.Number.SerializeToString,
            ),
            'getSqrt': grpc.unary_unary_rpc_method_handler(
                    servicer.getSqrt,
                    request_deserializer=calc__pb2.Number.FromString,
                    response_serializer=calc__pb2.Number.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'Calculator', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class Calculator(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def getSum(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/Calculator/getSum',
            calc__pb2.NumberTwo.SerializeToString,
            calc__pb2.Number.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def getProduct(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/Calculator/getProduct',
            calc__pb2.NumberTwo.SerializeToString,
            calc__pb2.Number.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def getDiff(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/Calculator/getDiff',
            calc__pb2.NumberTwo.SerializeToString,
            calc__pb2.Number.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def getDiv(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/Calculator/getDiv',
            calc__pb2.NumberTwo.SerializeToString,
            calc__pb2.Number.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def getSqrt(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/Calculator/getSqrt',
            calc__pb2.Number.SerializeToString,
            calc__pb2.Number.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
